# Generated by Django 5.2.8 on 2025-11-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RDPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(choices=[(4624, 'Login Successful'), (4647, 'User Initiated Logoff'), (4625, 'Login Failed'), (4779, 'Session Disconnect')])),
                ('username', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.CharField(blank=True, max_length=100)),
                ('workstation', models.CharField(blank=True, max_length=255)),
                ('raw_message', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('event_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
